apiVersion: v1
kind: Secret
metadata:
  name: yuxi-registry-secret
  namespace: yuxi
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "hub.uimpcloud.com": {
          "username": "<CHANGE_ME_REGISTRY_USERNAME>",
          "password": "<CHANGE_ME_REGISTRY_PASSWORD>",
          "auth": "<CHANGE_ME_BASE64_USERNAME_COLON_PASSWORD>"
        }
      }
    }
