apiVersion: v1
kind: Secret
metadata:
  name: yuxi-secret
  namespace: yuxi
type: Opaque
stringData:
  POSTGRES_USER: "<CHANGE_ME_POSTGRES_USER>"
  POSTGRES_PASSWORD: "<CHANGE_ME_POSTGRES_PASSWORD>"
  POSTGRES_DB: "<CHANGE_ME_POSTGRES_DB>"
  POSTGRES_URL: "postgresql+asyncpg://<CHANGE_ME_POSTGRES_USER>:<CHANGE_ME_POSTGRES_PASSWORD>@postgres:5432/<CHANGE_ME_POSTGRES_DB>"
  NEO4J_USERNAME: "<CHANGE_ME_NEO4J_USERNAME>"
  NEO4J_PASSWORD: "<CHANGE_ME_NEO4J_PASSWORD>"
  NEO4J_AUTH: "<CHANGE_ME_NEO4J_USERNAME>/<CHANGE_ME_NEO4J_PASSWORD>"
  MINIO_ACCESS_KEY: "<CHANGE_ME_MINIO_ACCESS_KEY>"
  MINIO_SECRET_KEY: "<CHANGE_ME_MINIO_SECRET_KEY>"
  SILICONFLOW_API_KEY: "<CHANGE_ME_SILICONFLOW_API_KEY>"
  TAVILY_API_KEY: "<CHANGE_ME_TAVILY_API_KEY>"
