apiVersion: v1
kind: Service
metadata:
  name: sandbox-provisioner
  namespace: yuxi
spec:
  type: ClusterIP
  selector:
    app: sandbox-provisioner
  ports:
    - name: http
      port: 8002
      targetPort: http

