apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data
  namespace: yuxi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-nfs
  resources:
    requests:
      storage: 10Gi
